name: Build and display  Image tag dev-us
on:
  pull_request:
    branches:
      - dev
jobs:
  extract-pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Parse and Validate PR Body
        id: parse_pr
        run: |
          # read the pull request body
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
          echo "PR_BODY=$PR_BODY"

          # Initialize selected environment variables
          DEV_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Dev: `)[^`]+')
         
          echo "DEV_SELECTED=$DEV_SELECTED" >> $GITHUB_ENV
          # Extract image tags for each region
          DEV_IMAGE_US=$(echo "$PR_BODY" | grep -A 3 "Dev Environment" | grep "US Region:" | awk -F'`' '{print $2}' | tr -d '[:space:]')
         
          # Export image tags to the environment
          echo "DEV_IMAGE_US=$DEV_IMAGE_US" >> $GITHUB_ENV

      - name: Validate and Display Selected Environments
        run: |
          echo "Selected Environments:"
          if [ "$DEV_SELECTED" == "Y" ]; then
            if [ -z "$DEV_IMAGE_US" ] ; then
              echo "Error: Missing image tag values for Dev Environment."
              exit 1
            fi
            echo "Dev: US=$DEV_IMAGE_US"
          fi

         
