name: Build and display  Image tag PROD-US
on:
  pull_request:
    branches:
      - prod
jobs:
  extract-pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Parse and Validate PR Body
        id: parse_pr
        run: |
          # read the pull request body
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
          echo "PR_BODY=$PR_BODY"

          # Initialize selected environment variables
          PROD_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Prod: `)[^`]+')
         
          echo "PROD_SELECTED=$PROD_SELECTED" >> $GITHUB_ENV
          # Extract image tags for each region
          PROD_IMAGE_US=$(echo "$PR_BODY" | grep -A 3 "PROD Environment" | grep "US Region:" | awk -F'`' '{print $2}' | tr -d '[:space:]')
         
          # Export image tags to the environment
          echo "PROD_IMAGE_US=$PROD_IMAGE_US" >> $GITHUB_ENV

      - name: Validate and Display Selected Environments
        run: |
          echo "Selected Environments:"
          if [ "$PROD_SELECTED" == "Y" ]; then
            if [ -z "$PROD_IMAGE_US" ] ; then
              echo "Error: Missing image tag values for PROD Environment."
              exit 1
            fi
            echo "PROD: US=$PROD_IMAGE_US"
          fi

         
