name: Build and display  Image tag staging-AP
on:
  pull_request:
    branches:
      - staging
jobs:
  extract-pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Parse and Validate PR Body
        id: parse_pr
        run: |
          # read the pull request body
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
          echo "PR_BODY=$PR_BODY"

          # Initialize selected environment variables
          STAGING_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Staging: `)[^`]+')
         
          echo "STAGING_SELECTED=$STAGING_SELECTED" >> $GITHUB_ENV
          # Extract image tags for each region
          STAGING_IMAGE_AP=$(echo "$PR_BODY" | grep -A 3 "STAGING Environment" | grep "AP Region:" | awk -F'`' '{print $2}' | tr -d '[:space:]')
         
          # Export image tags to the environment
          echo "STAGING_IMAGE_AP=$STAGING_IMAGE_AP" >> $GITHUB_ENV

      - name: Validate and Display Selected Environments
        run: |
          echo "Selected Environments:"
          if [ "$STAGING_SELECTED" == "Y" ]; then
            if [ -z "$STAGING_IMAGE_AP" ] ; then
              echo "Error: Missing image tag values for STAGING Environment."
              exit 1
            fi
            echo "STAGING: AP=$STAGING_IMAGE_AP"
          fi

         
