name: Build and Push Docker Image to Docker Hub-staging-US
on:
  pull_request:
    branches:
      - staging

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Parse and Validate PR Body
        id: parse_pr
        run: |
          # read the pull request body
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
          echo "PR_BODY=$PR_BODY"

          # Initialize selected environment variables
          
          STAGING_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Staging: `)[^`]+')
        
          echo "STAGING_SELECTED=$STAGING_SELECTED" >> $GITHUB_ENV
          
          STAGING_IMAGE_US=$(echo "$PR_BODY" | grep -A 3 "Staging Environment" | grep "US Region:" | awk -F'`' '{print $2}' | tr -d '[:space:]')
          
          # Export image tags to the environment
         
          echo "STAGING_IMAGE_US=$STAGING_IMAGE_US" >> $GITHUB_ENV
          

      - name: Validate and Display Selected Environments
        run: |
          echo "Selected Environments:"

         

          if [ "$STAGING_SELECTED" == "Y" ]; then
            if [ -z "$STAGING_IMAGE_US" ]; then
              echo "Error: Missing image tag values for Staging Environmensts."
              exit 1
            fi
            echo "Staging: US=$STAGING_IMAGE_US"
          fi

        
